baseURL = 'https://manpreet.fyi/'
languageCode = 'en-us'
title = 'Manpreet Kunnath'
theme = 'nightfall'

[menu]
  [[menu.header]]
    name = "portfolio"
    weight = 1
    url = "https://portfolio.manpreet.fyi/"
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "posts"

[params]
  user = ""
  hostname = "manpreet.fyi"
[params.author]
  name = "Manpreet Kunnath"
  email = "m@manpreet.fyi"

[[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/mvk059"
  target = "_blank"
  aria = "GitHub Profile"

[[params.social]]
	key = 1
	name = "twitter"
	url = "https://x.com/manpreetkunnath"
	target = "_blank"
	aria = "Twitter Profile"

[[params.social]]
	key = 2
	name = "linkedin"
	url = "https://linkedin.com/in/manpreetkunnath"
	target = "_blank"
	aria = "LinkedIn Profile"

[[params.social]]
	key = 3
	name = "email"
	url = "mailto:m@manpreet.fyi"
	aria = "My e-Mail Address"
